Acme\FrontBundle\Entity\TbAluno:
    type: entity
    table: tb_aluno
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nome:
            type: string
            length: 255
            fixed: false
            nullable: false
        email:
            type: string
            length: 255
            fixed: false
            nullable: false
        telefone:
            type: string
            length: 255
            fixed: false
            nullable: false
    manyToOne:
        filial:
            targetEntity: TbFilial
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                filial_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
